### ISSUE TITLE
Update services content on about us page

### ISSUE THREAD

**Issue by shanda-eclipse** [EclipseFdn/eclipse.org#10]
On https://www.eclipse.org/org/

Please link "services" to https://www.eclipse.org/org/services/ and add "and Marketing" to:

The Eclipse Foundation provides four key **services** to the Eclipse community: 1) IP Management, 2) Ecosystem Development **and Marketing**, 3) Development Process, and 4) IT Infrastructure. Full-time staff are associated with each of these areas and work with the greater Eclipse community to assist in meeting the needs of stakeholders.

**Comment by autumnfound** [comment]
Please see staging for the update to this section https://staging.eclipse.org/org/services/ !

**Comment by shanda-eclipse** [comment]
+1

**Comment by shanda-eclipse** [comment]
sorry +1 for the changes to https://staging.eclipse.org/org/services/

I don't see changes on https://staging.eclipse.org/org/ yet.

**Comment by autumnfound** [comment]
> sorry +1 for the changes to https://staging.eclipse.org/org/services/
> 
> I don't see changes on https://staging.eclipse.org/org/ yet.

Apologies, I missed that. I've updated this to be consistent with the other content on this page, in that there are no links in headers. Links to sections in the same page are available just below still as expected.

**Comment by shanda-eclipse** [comment]
+1 Thanks for moving so quickly on this one!
