### ISSUE TITLE
Updates to https://www.eclipse.org/org/services/#Ecosystem

### ISSUE THREAD

**Issue by shanda-eclipse** [EclipseFdn/eclipse.org#11]
Please update the Ecosystem Development section on https://www.eclipse.org/org/services/#Ecosystem to:

**Ecosystem Development and Marketing**
The Eclipse Foundation’s vendor-neutral ecosystem development and marketing programs promote community and membership growth, drive awareness and discoverability of projects and working groups, and increase the commercial adoption of Eclipse technologies. 
The Eclipse Foundation coordinates and implements a variety of activities, including content creation, press and analyst relations, community conferences and events, advertising, social media management, and other programs to promote the entire Eclipse community and increase engagement.

**Comment by autumnfound** [comment]
@shanda-eclipse I've updated staging with this change along with #10. Have a look and let me know if everything looks good! https://staging.eclipse.org/org/services/#Ecosystem

**Comment by shanda-eclipse** [comment]
+1
