### ISSUE TITLE
Membership Page Update

### ISSUE THREAD

**Issue by meKokabi** [EclipseFdn/eclipse.org#12]
Please update this page: https://www.eclipse.org/membership/  as shown on screen shots
New content that need to be replaced :
ECOSYSTEM DEVELOPMENT AND MARKETING
"The Eclipse Foundation’s vendor-neutral marketing programs promote Eclipse community growth and engagement, drive awareness and discoverability of projects and working groups and increase the commercial adoption of Eclipse technologies. The Foundation coordinates and implements a variety of activities, including content creation, press and analyst relations, community conferences and events, advertising, social media management, and other programs to promote the entire Eclipse community and increase engagement."
<img width="817" alt="Screen Shot 2021-03-30 at 9 53 27 AM" src="https://user-images.githubusercontent.com/75500459/113001871-3b5f4a80-913f-11eb-8903-b3aab3d90450.png">

Thanks!

**Comment by meKokabi** [comment]
<img width="884" alt="Screen Shot 2021-03-30 at 3 00 55 PM" src="https://user-images.githubusercontent.com/75500459/113042254-f51ee100-9168-11eb-9c04-55731e36c31d.png">


Please also update the download button links with attached PDF
[EF Membership Prospectus-Presentation (1).pdf](https://github.com/EclipseFdn/eclipse.org/files/6231570/EF.Membership.Prospectus-Presentation.1.pdf)

**Comment by autumnfound** [comment]
@meKokabi see staging (https://staging.eclipse.org/membership/) for the updated text, let me know if you need any further changes!

**Comment by meKokabi** [comment]
Can you please check the styling and make sure the line spacing is correct?
Consistent with other 3 boxes. Thanks

**Comment by autumnfound** [comment]
There is no difference in line spacing, its the same stuff that wraps all 4 of those sections. The text is just longer which forces the container to be larger

**Comment by chrisguindon** [comment]
Are we good to merge the changes in production or is this still a WIP?

**Comment by meKokabi** [comment]
> Are we good to merge the changes in production or is this still a WIP?

I believe it is good to move to the production. Thank You All!

**Comment by autumnfound** [comment]
This is live on production!
