### ISSUE TITLE
Content Update on https://www.eclipse.org/org/artwork/

### ISSUE THREAD

**Issue by meKokabi** [EclipseFdn/eclipse.org#14]
Hi, 
Please add the OpenAdx logo on https://www.eclipse.org/org/artwork/ under the working group section.
The  logos variations zip folder enclosed here
Thanks!

[OpenADx.zip](https://github.com/EclipseFdn/eclipse.org/files/7236523/OpenADx.zip)

**Comment by linkfang** [comment]
Hi @meKokabi ,
Please preview the changes here:
https://staging.eclipse.org/org/artwork/

username: testuser
password: plaintext

**Comment by meKokabi** [comment]
Thanks Zhou! looks good!

**Comment by linkfang** [comment]
No problem!
Now the changes are live!
