### ISSUE TITLE
Explore our working group page content update

### ISSUE THREAD

**Issue by meKokabi** [EclipseFdn/eclipse.org#15]
Hi,
Would you please update these logos at: https://www.eclipse.org/org/workinggroups/explore.php
Logos that need update:
Jakarta EE,  Adoptium, Cloud Dev Tools, Edge Native, OpenADx, 
openMDM, openMobility, openPASS, Sparkplug, Tangle EE

FYR: The updated logos are with trademark or registration codes.

Thanks,

[Logos-SVG.zip](https://github.com/EclipseFdn/eclipse.org/files/7253069/Logos-SVG.zip)

**Comment by ericpoirier** [comment]
Hi @meKokabi, would it be possible for you to crop some of the svg you provided? Some of the are a lot bigger than the actual logo. For example, OpenPass's svg is currenty 1000x1000px.

Thanks.

**Comment by meKokabi** [comment]
Hi @ericpoirier sure, just need time to do it, as I just worked on their symbols, and most of them are from original files stored on shareDrive. But will work on them and get back to you shortly. As we got a request from Sharon for common look and presentation among all the logos.

**Comment by meKokabi** [comment]
in case you have any specific suggestion to make them more consistent please let me know.

**Comment by ericpoirier** [comment]
> in case you have any specific suggestion to make them more consistent please let me know.

it's really juste a matter of removing the blank space around the logos. Most of them are fine, I just found OpenPass that was pretty big.

**Comment by meKokabi** [comment]
Oh Ok I will fix it now

**Comment by meKokabi** [comment]
[OpenPassLogo.zip](https://github.com/EclipseFdn/eclipse.org/files/7254178/OpenPassLogo.zip)

**Comment by meKokabi** [comment]
@ericpoirier Please let me know if any other ones need resizing.

**Comment by ericpoirier** [comment]
> @ericpoirier Please let me know if any other ones need resizing.

Thanks!

**Comment by meKokabi** [comment]
😊

**Comment by meKokabi** [comment]
@slcorbett has been added  to the bug.

**Comment by meKokabi** [comment]
@SharonCorbett  FYR

**Comment by linkfang** [comment]
Hi @meKokabi ,

The Adopitum logo also has a fairly large blank spaces around the logo making it a little too small on the page.
Can you also adjust it please? Thanks!
![image](https://user-images.githubusercontent.com/43075439/135670858-8cc2c587-0801-464a-9716-ce0e31b2a983.png)

**Comment by meKokabi** [comment]
Hi @linkfang Here You Are
[AdoptiumSvg.zip](https://github.com/EclipseFdn/eclipse.org/files/7269483/AdoptiumSvg.zip)

**Comment by linkfang** [comment]
Awesome!
Please preview the changes here:
https://staging.eclipse.org/org/workinggroups/explore.php

**Comment by meKokabi** [comment]
Thanks! please proceed to make it live.

**Comment by SharonCorbett** [comment]
I do not see anything for Adoptium and Sparkplug.  Is it just me?

**Comment by linkfang** [comment]
> I do not see anything for Adoptium and Sparkplug. Is it just me?

I can see them. 
Can you try to open the page in Incognito mode? Maybe it's a cache issue.
![image](https://user-images.githubusercontent.com/43075439/135682081-a4ff4b40-0a52-4601-ab77-4ddc70a94630.png)

**Comment by SharonCorbett** [comment]
Nope - that didn't work either and on second glance none of the updates are there.  I've refreshed several times.

I'm using Chrome?

**Comment by linkfang** [comment]
Are you checking the changes on staging? 
https://staging.eclipse.org/org/workinggroups/explore.php

They are not live yet, as the code review is not done. Will need to go live the coming Monday, I think.

**Comment by SharonCorbett** [comment]
Zhou:  Thanks as usual!  All is good...

And since you guys got this, I'll just wish you both a happy weekend!

**Comment by linkfang** [comment]
Cool, no problem!

Thanks, you too!

**Comment by linkfang** [comment]
Now the changes are live!
