### ISSUE TITLE
Update Edge Native Logo on https://www.eclipse.org/org/workinggroups/explore.php

### ISSUE THREAD

**Issue by hudsonkelly83** [EclipseFdn/eclipse.org#3]
Hello, would it be possible to update the Edge Native Logo on https://www.eclipse.org/org/workinggroups/explore.php to reflect the new update?

Here is the updated image. 

Thanks! 

![image](https://user-images.githubusercontent.com/70344546/104624592-c3b27100-5661-11eb-8408-7f8133ab7e6a.png)

**Comment by flora8984461** [comment]
Hi @mbarbero 
Please check the staging preview: https://staging.eclipse.org/org/workinggroups/explore.php

user: testuser
pass: plaintext

Thanks!

**Comment by autumnfound** [comment]
I think you meant @hudsonkelly83 ;)

**Comment by flora8984461** [comment]
Oh! Sorry, the other two issues are from her, I mentioned wrongly. Sorry again! @hudsonkelly83

**Comment by mbarbero** [comment]
No worries ;)

**Comment by hudsonkelly83** [comment]
Looks great to me! Thanks again Yi!

**Comment by flora8984461** [comment]
The change is live on prod. I'm going to mark this as resolved, please feel free to reopen if more changes needed. Thanks!
