### ISSUE TITLE
Update membership page resources

### ISSUE THREAD

**Issue by meKokabi** [EclipseFdn/eclipse.org#4]
Hello,
Would you please update the Download Button's link that is under presentation overview with the attached pdf. 
(Just for your reference here is a screenshot of the button<img width="378" alt="Screen Shot 2021-01-18 at 2 06 36 PM" src="https://user-images.githubusercontent.com/75500459/104954819-0abca100-5997-11eb-8d95-aeeb1d3ec286.png">)

link to the page: https://www.eclipse.org/membership/#tab-resources
(The new pdf mostly has update on the footer).
[Eclipse Foundation Corporate Presentation - v2021-01 (1).pdf](https://github.com/EclipseFdn/eclipse.org/files/5832049/Eclipse.Foundation.Corporate.Presentation.-.v2021-01.1.pdf)
Thanks for your support,
M

**Comment by flora8984461** [comment]
Hi @meKokabi , thanks for providing the PDF. I wonder if you have a smaller size version? The current PDF is 13.7MB. We hope to keep the server light.

Thanks!

**Comment by meKokabi** [comment]
Here You Are! This is much lighter.
[Eclipse Foundation Corporate Presentation - v2021-01 (1)-compressed.pdf](https://github.com/EclipseFdn/eclipse.org/files/5837263/Eclipse.Foundation.Corporate.Presentation.-.v2021-01.1.-compressed.pdf)

**Comment by flora8984461** [comment]
> Here You Are! This is much lighter.
> [Eclipse Foundation Corporate Presentation - v2021-01 (1)-compressed.pdf](https://github.com/EclipseFdn/eclipse.org/files/5837263/Eclipse.Foundation.Corporate.Presentation.-.v2021-01.1.-compressed.pdf)

Thanks, just to confirm, 4MB is the smallest? Thanks!

**Comment by meKokabi** [comment]
Yes it was almost 14 MB and I compressed it to 4

**Comment by flora8984461** [comment]
Hi @meKokabi the change is live, please check https://www.eclipse.org/membership/#tab-resources.

I'm going to mark this as resolved, please feel free to reopen if more changes needed, thanks!

**Comment by meKokabi** [comment]
Appreciated!
