### ISSUE TITLE
Logo Audit/Page Update

### ISSUE THREAD

**Issue by meKokabi** [EclipseFdn/eclipse.org#5]
Hello,
Please update 2 logos on this page: https://www.eclipse.org/org/workinggroups/explore.php
Logos need to update:
1- ECLIPSE CLOLUD DEV TOOLS
2- OSGI Logo
![OSGi_Alliance_RGB_V2 copy](https://user-images.githubusercontent.com/75500459/108393813-0841a700-71e2-11eb-9901-c3746f9c2289.png)
![ECD Tools Logo Horizontal Orange](https://user-images.githubusercontent.com/75500459/108393857-11cb0f00-71e2-11eb-891f-52482e9b8e2f.png)

**Comment by flora8984461** [comment]
The patch is https://git.eclipse.org/r/c/www.eclipse.org/org/+/176554 

Current staging is taken by another PR

**Comment by flora8984461** [comment]
Hi @meKokabi 

Please check the preview on staging: https://staging.eclipse.org/org/workinggroups/explore.php

We will merge to live once +1 from you.

Thanks!

**Comment by meKokabi** [comment]
Hi Yi,
Thanks, looks great!

**Comment by flora8984461** [comment]
The change is live, please check https://www.eclipse.org/org/workinggroups/explore.php

I'm going to close this issue, please feel free to reopen if more changes needed.

Thanks!
