### ISSUE TITLE
Content Update on The Eclipse Logos and Artwork page

### ISSUE THREAD

**Issue by meKokabi** [EclipseFdn/eclipse.org#6]
Hello, 
Please update this page: https://www.eclipse.org/artwork/   

1- Add 3 logos including OpenADx, MicroProfile, OSGI. The required files has been attached for each logo. 
2- Delete the LocationTech and LTS logos as they are no longer with us.

[Microprofile logos.zip](https://github.com/EclipseFdn/eclipse.org/files/6031010/Microprofile.logos.zip)
[OpenADx.zip](https://github.com/EclipseFdn/eclipse.org/files/6031011/OpenADx.zip)
[OSGi LOGO .zip](https://github.com/EclipseFdn/eclipse.org/files/6031012/OSGi.LOGO.zip)

Thanks for your time and support,

**Comment by flora8984461** [comment]
Hi, @chrisguindon Question: Do I need to remove the zip files and logo files for LocationTech and LTS?

Hi, @meKokabi Please check the preview on staging: https://staging.eclipse.org/artwork/

Thanks!

**Comment by meKokabi** [comment]
@flora8984461 Hello, Thanks for updating the page, just one question/concern about the logos sizes on the page, some got so large while others are small. I believe there is an option to make them same sizes, right?

**Comment by flora8984461** [comment]
@meKokabi Thanks for the feedback. I have adjusted the image size, and please check the preview on staging:
https://staging.eclipse.org/artwork/

Currenly, I set them all to "width=200". 

Thanks!

**Comment by meKokabi** [comment]
Looks great! Thank You!

**Comment by chrisguindon** [comment]
I committed the work done by @flora8984461 

It should be live any minute now!
