### ISSUE TITLE
Update Automotive flyer with New pdf

### ISSUE THREAD

**Issue by meKokabi** [EclipseFdn/eclipse.org#8]
Please update the new attached pdf version that need to be uploaded to this URL: https://www.eclipse.org/org/workinggroups/documents/automotive_flyer.pdf

[AutomotiveFlyer_2021.pdf](https://github.com/EclipseFdn/eclipse.org/files/6216173/AutomotiveFlyer_2021.pdf)

Thanks

**Comment by autumnfound** [comment]
I've merged this in, sorry for the delay!
