### ISSUE TITLE
Content Update for Press Release Guidelines Page 

### ISSUE THREAD

**Issue by meKokabi** [EclipseFdn/eclipse.org#9]
Please update the content of this page: 
https://www.eclipse.org/org/press-release/pressrelease_guidelines.php
with the following: https://docs.google.com/document/d/1nnTFsx5K19UPwbEvcqNfUVxfdM88Thr8JSYxDwlUfwQ/edit#heading=h.1pt55nxiro71

[Press Release Guidelines - v2021-03.docx](https://github.com/EclipseFdn/eclipse.org/files/6213854/Press.Release.Guidelines.-.v2021-03.docx)
Thanks

**Comment by shanda-eclipse** [comment]
@chrisguindon would we be able to prioritize this for early next week? We were hoping to share the update in the member newsletter that goes out on Thurs April 15.

**Comment by chrisguindon** [comment]
@shanda-eclipse 

@autumnfound can you make sure to work on this early next week please?

**Comment by autumnfound** [comment]
A patch has been created for this https://git.eclipse.org/r/c/www.eclipse.org/org/+/179218. Staging is currently in use for a patch for a working group document, I'll post here once I can push the patch to staging with a link

**Comment by autumnfound** [comment]
This has been pushed to staging, let me know if there are any changes you need, or if its good to go! https://staging.eclipse.org/org/press-release/pressrelease_guidelines.php

**Comment by meKokabi** [comment]
Thanks Martin. Can you please increase the line spacing for this
subheading: "Company Releases a Commercial Product Based on/Integrated with
Eclipse-Governed Technologies or a Product Certified Compatible with an
Eclipse Foundation Specification"

**Comment by shanda-eclipse** [comment]
@autumnfound Can we push this live this morning?

**Comment by autumnfound** [comment]
I'll add a little line spacing to the mentioned subheading and I'll get it live!

**Comment by meKokabi** [comment]
Perfect! Thank You!

**Comment by autumnfound** [comment]
This is live now! https://www.eclipse.org/org/press-release/pressrelease_guidelines.php
